import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: '#f5f5f5',
    flex: 1,
  },

  headerBox: {
    backgroundColor: '#0047AB',
    padding: 14,
    borderRadius: 10,
    marginVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },

  rowBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  // halfCard: { width: '48%', padding: 16 },
  // cardTitle: { fontWeight: 'bold', fontSize: 16 },
  // cardText: { fontSize: 14, marginTop: 4 },
  // amountButton: { marginTop: 10, borderRadius: 10 },
  halfCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    marginBottom: 16,
    gap: 6,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 6,
  },
  cardText: {
    fontSize: 14,
    color: '#444',
    marginVertical: 2,
  },
  amountButton: {
    marginTop: 10,
    alignSelf: 'flex-end',
    backgroundColor: '#0d6efd',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 1,
    fontSize: 16,
  },

  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 10,
    marginLeft: 6,
  },
  documentCard: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 120,
    height: 100,
    borderRadius: 10,
    borderColor: '#ddd',
    borderWidth: 1,
    marginHorizontal: 6,
    padding: 10,
    backgroundColor: '#fff',
  },
  documentLabel: {
    fontWeight: '600',
    fontSize: 13,
    marginTop: 8,
    textAlign: 'center',
    color: '#333',
  },

  profileCard: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    marginBottom: 20,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  userName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
  },
  userExperience: {
    fontSize: 14,
    color: '#555',
    marginTop: 4,
  },
  skillCard: {
    flex: 1,
    margin: 6,
    padding: 12,
    borderRadius: 10,
    backgroundColor: '#f9f9f9',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  skillText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '600',
  },
  expText: {
    fontSize: 12,
    color: '#777',
    marginTop: 6,
  },

  // profileCard: {padding: 16, marginVertical: 20},
  // profileHeader: {flexDirection: 'row', alignItems: 'center', marginBottom: 16},
  // userName: {fontWeight: 'bold', fontSize: 16},
  // userExperience: {color: '#777', fontSize: 14},
  // skillCard: {
  //   flex: 1,
  //   margin: 8,
  //   padding: 12,
  //   backgroundColor: '#f3f3f3',
  //   borderRadius: 10,
  // },
  // skillText: {fontWeight: 'bold', fontSize: 14},
  // expText: {color: '#555', marginTop: 6},
});
